version: '3.7'

services:
    traefik:
        image: traefik:latest
        container_name: traefik
        restart: always
        ports:
            - 80:80
            - 443:443
            - 8100:8080
        labels:
            traefik.enable: true
            traefik.frontend.rule: "Host:traefik.${DOMAIN1}"
            traefik.frontend.auth.basic: "master:$$apr1$$EfBTn744$P73vgx5dek0FPXnWMoalG0"
            traefik.port: 8100
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik/traefik.toml:/traefik.toml
            - ./traefik/acme.json:/acme.json
        networks:
            - web

    mongo:
        image: mongo
        container_name: unifidb
        restart: unless-stopped
        volumes:
            - ./mongodb/db:/data/db
        networks:
            - web

    unifi:
        image: goofball222/unifi
        container_name: unifi
        restart: unless-stopped
        links:
            - mongo
        ports:
            - 6789:6789
            - 8080:8080
            - 8081:8081
            - 8880:8880
            - 8443:8443
            - 8843:8843
            - 3478:3478/udp
            - 10001:10001/udp
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./traefik/unifi:/config
            - ./traefik:/shared
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - DB_MONGO_LOCAL=false
            - DB_MONGO_URI=mongodb://mongo:27017/unifi
            - STATDB_MONGO_URI=mongodb://mongo:27017/unifi_stat
            - TZ=Europe/Stockholm
            - UNIFI_DB_NAME=unifi
        networks:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.backend=unifi"
            - "traefik.frontend.rule=Host:unifi.${DOMAINNAME}"
            - "traefik.port=8443"
            - "traefik.protocol=https"
            - "traefik.docker.network=traefik_proxy"
            - "traefik.frontend.headers.SSLRedirect=true"
            - "traefik.frontend.headers.STSSeconds=315360000"
            - "traefik.frontend.headers.browserXSSFilter=true"
            - "traefik.frontend.headers.contentTypeNosniff=true"
            - "traefik.frontend.headers.forceSTSHeader=true"
            - "traefik.frontend.headers.SSLHost=unifi.${DOMAINNAME}"
            - "traefik.frontend.headers.SSLForceHost=true"
            - "traefik.frontend.headers.STSIncludeSubdomains=true"
            - "traefik.frontend.headers.STSPreload=true"
            - "traefik.frontend.headers.frameDeny=true"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.frontend.auth.forward.address=http://oauth:4181"


    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30

networks:
    web:
        external: true