version: '3.7'

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 8080:8080 #Close this port once you verify traefik.domain.tld works
    command: 
      - "--logLevel=WARN"
      - "--ping=false"
      - "--api"
      - "--api.entrypoint=apiport"
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS TLS.SniStrict:true TLS.MinVersion:VersionTLS12 CipherSuites:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
      - "--entrypoints=Name:apiport Address::8080"
      - "--acme"
      - "--acme.acmelogging" 
      - "--acme.storage=/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.dnsChallenge=true"
      - "--acme.dnsChallenge.provider=godaddy"
      - "--acme.dnsChallenge.delayBeforeCheck=60"
      - "--acme.onHostRule=true"
      - "--acme.email=${EMAIL}"
      - "--acme.acmeLogging=true"
      - "--acme.domains=${DOMAINNAME},*.${DOMAINNAME},${DOMAINNAME2},"
      - "--acme.KeyType=RSA4096"
      - "--docker"
      - "--docker.domain=${DOMAINNAME}"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--retry"
#      - "--file"
      - "resolvers=[192,168.1.1:53,1.1.1.1:53,]"
    environment:
      TZ: ${TZ}
      CLOUDFLARE_EMAIL: ${EMAIL}
      CLOUDFLARE_API_KEY: ${CFKEY}
    labels:
      traefik.enable: "true"
      traefik.backend: traefik
      traefik.frontend.rule: "Host:traefik.${DOMAIN1}"
      traefik.port: 8080
      traefik.frontend.auth.basic: "master:$$apr1$$EfBTn744$P73vgx5dek0FPXnWMoalG0"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.headers.SSLForceHost: "true"
      traefik.frontend.headers.SSLHost: traefik.${DOMAINNAME}
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny: "true"
      traefik.frontend.headers.customFrameOptionsValue: 'allow-from https://${DOMAINNAME}'
#  Added Front add for when we shift you off of auth.basic
#        traefik.frontend.auth.forward.address: http://traefik-forward-auth:4181
#        traefik.frontend.auth.forward.authResponseHeaders: X-Forwarded-User
#        traefik.frontend.auth.forward.trustForwardHeader: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
#      - ./traefik/rules.toml:/rules.toml
    restart: always

  mongo:
    image: mongo
    container_name: unifidb
    restart: unless-stopped
    volumes:
      - ./mongodb/db:/data/db
    networks:
      - web

  unifi:
    image: goofball222/unifi
    container_name: unifi
    restart: unless-stopped
    links:
      - mongo
    ports:
      - 6789:6789
      - 8080:8080
      - 8081:8081
      - 8880:8880
      - 8443:8443
      - 8843:8843
      - 3478:3478/udp
      - 10001:10001/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik/unifi:/config
      - ./traefik:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_MONGO_LOCAL=false
      - DB_MONGO_URI=mongodb://mongo:27017/unifi
      - STATDB_MONGO_URI=mongodb://mongo:27017/unifi_stat
      - TZ=Europe/Stockholm
      - UNIFI_DB_NAME=unifi
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=unifi"
      - "traefik.frontend.rule=Host:unifi.${DOMAINNAME}"
      - "traefik.port=8443"
      - "traefik.protocol=https"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=unifi.${DOMAINNAME}"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.auth.forward.address=http://oauth:4181"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
