version: '3.7'
services:
    nzbget:
        image: linuxserver/nzbget:latest
        container_name: nzbget
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
        volumes:
            - ./nzbget:/config
            - Media:/media
        ports:
            - 8082:6789
        cap_add:
            - NET_ADMIN
        restart: unless-stopped

    sabnzbd:
        image: linuxserver/sabnzbd:latest
        container_name: sabnzbd
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
        volumes:
            - ./sabnzbd:/config
            - Media:/plexmedia
        ports:
            - 8080:8080
            - 9090:9090
        restart: unless-stopped

    transmission:
        image: haugene/transmission-openvpn:latest
        container_name: transmission
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        restart: always
        ports:
            - 9091:9091
            - 8888:8888
        dns:
            - 46.227.67.134
            - 192.165.9.158
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - Media:/data
        environment:
            - OPENVPN_PROVIDER=OVPN
            - OPENVPN_USERNAME=ratnose
            - OPENVPN_PASSWORD=KLY-PNq-uu5-RX8
            - LOCAL_NETWORK=10.20.1.0/24

    proxy:
        image: haugene/transmission-openvpn-proxy:latest
        container_name: transmission_proxy
        links:
            - transmission
        ports:
            - 8800:8080
        volumes:
            - /etc/localtime:/etc/localtime:ro

    sonarr:
        image: linuxserver/sonarr:preview
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
        volumes:
            - ./sonarr:/config
            - Media:/plexbase
        restart: unless-stopped
        ports:
            - 8090:8989

    couchpotato:
        image: linuxserver/couchpotato:latest
        container_name: couchpotato
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
            - UMASK_SET=022
        volumes:
            - ./couchpotato:/config
            - Media:/media
        ports:
            - 5050:5050
        restart: unless-stopped

    muximux:
        image: linuxserver/muximux:latest
        container_name: muximux
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
        volumes:
            - ./muximux:/config
        restart: unless-stopped
        ports:
            - 80:80

    ombi:
        container_name: ombi
        image: linuxserver/ombi
        restart: unless-stopped
        networks:
            - traefik_proxy
    #    ports:
    #      - "80:80"
        volumes:
            - ${USERDIR}/ombi:/config
            - ${USERDIR}/shared:/shared
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
        labels:
            - "traefik.enable=true"
            - "traefik.backend=organizr"
            - "traefik.frontend.rule=Host:ombi.${DOMAINNAME}"
            - "traefik.port=80"
            - "traefik.docker.network=traefik_proxy"
            - "traefik.frontend.headers.SSLRedirect=true"
            - "traefik.frontend.headers.STSSeconds=315360000"
            - "traefik.frontend.headers.browserXSSFilter=true"
            - "traefik.frontend.headers.contentTypeNosniff=true"
            - "traefik.frontend.headers.forceSTSHeader=true"
            - "traefik.frontend.headers.SSLHost=organizr.${DOMAINNAME}"
            - "traefik.frontend.headers.SSLForceHost=true"
            - "traefik.frontend.headers.STSIncludeSubdomains=true"
            - "traefik.frontend.headers.STSPreload=true"
            - "traefik.frontend.headers.frameDeny=true"
            - "traefik.frontend.auth.forward.address=http://oauth:3579"

    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 30

volumes:
  Media:
    driver_opts:
      type: "nfs"
      o: "addr=10.20.1.90,rw,soft"
      device: ":/mnt/storage/plexmedia/"
