
[api]
  entryPoint = "traefik"
  dashboard = true
  
logLevel = "WARN"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    MinVersion = "VersionTLS12"
    CipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256","TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"]

[retry]

[acme]
acmeLogging = true
email = "mattias.hedman@gmail.com"
storage = "/acme.json"
entryPoint = "https"
  [acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = "60"

[[acme.domains]]
   main = "grillgeek.se"
[[acme.domains]]
   main = "*.grillgeek.se"
[[acme.domains]]
   main = "sundsvallbbq.se"

[file]
  filename = "/rules.toml"
  watch = false #change to true once you need it.

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "grillgeek.se"
  watch = true
  exposedbydefault = false
