version: '3.7'
    plex:
        image: linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
        volumes:
            - ./appdata/plex/:/config
            - ./appdata/plex/transcode:/transcode
            - Plexmedia:/plexmedia
        restart: unless-stopped
        ports:
            - 32400:32400

    mariadb:
        image: linuxserver/mariadb
        container_name: mariadb
        environment:
            - PUID=1000
            - PGID=1000
            - MYSQL_ROOT_PASSWORD=9zmq893FF!!9zmq893f
            - TZ=Europe/Stockholm
        volumes:
            - ./appdata/mariadb:/config
        ports:
            - 3306:3306
        restart: unless-stopped

    cloud:
        image: linuxserver/nextcloud:latest
        container_name: cloud
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
        volumes:
            - ./appdata/cloud:/config
            - Nextcloud:/data
        ports:
           - 8040:80
           - 8043:443
        depends_on:
            - mariadb
        restart: unless-stopped

    adminer:
        image: adminer
        container_name: adminer
        restart: unless-stopped
        ports:
            - 8181:8080

    ombi:
        image: linuxserver/ombi
        container_name: ombi
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
            - BASE_URL=ombi.grillgeek.se
        volumes:
            - ./appdata/ombi/:/config
        ports:
            - 3579:3579
        restart: unless-stopped
    
    unifi-controller:
        image: linuxserver/unifi-controller:latest
        container_name: unifi-controller
        environment:
            - PUID=1000
            - PGID=1000
            - MEM_LIMIT=1024M
        volumes:
            - ./appdata/unifi:/config
        ports:
            - 443:443/tcp
            - 443:443/udp
            - 3478:3478/udp
            - 1900:1900/udp
            - 10001:10001/udp
            - 8080:8080
            - 8081:8081
            - 8443:8443
            - 8843:8843
            - 8880:8880
            - 8883:8883
            - 6789:6789
        restart: unless-stopped

volumes:
    Nextcloud:
        driver_opts:
            type: "nfs"
            o: "addr=10.20.1.90,rw,soft"
            device: ":/mnt/storage/nextcloud"

    Plexmedia:
        driver_opts:
            type: "nfs"
            o: "addr=10.20.1.90,rw,soft"
            device: ":/mnt/storage/plexmedia"